#!/bin/sh

jar -cMf scsynth-clj-native-deps-0.0.1-SNAPSHOT.jar native
mvn install:install-file -Dfile=scsynth-clj-native-deps-0.0.1-SNAPSHOT.jar \
			 -DgroupId=overtone \
                         -DartifactId=scsynth-clj-native-deps \
                         -Dversion=0.0.1-SNAPSHOT -Dpackaging=jar
